<?php

namespace App\Services;

use App\Jobs\GenerateForecastSnapshot;
use App\Models\JobOrder;
use App\Models\SaleItem;
use App\Services\Forecasting\Sarima;
use Illuminate\Support\Carbon;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Cache;

class ForecastService
{
    private const Z_SCORES = [90 => 1.645, 95 => 1.96, 99 => 2.576];

    private const SEASONAL_PERIOD = 12;

    /**
     * Reuse the same forecast payload within a single page render to avoid re-running the
     * expensive Python SARIMA work multiple times for the same metric/confidence pair.
     */
    private array $computeCache = [];

    // The SARIMA grid search + hold-out backtest are the expensive part of this page (a full
    // grid search per call). Both depend only on the metric's history, not on forecastMonths or
    // confidence, so they're cached per metric and keyed off a fingerprint of the series itself —
    // the cache self-invalidates whenever the underlying data changes, no manual bust needed.
    private const MODEL_CACHE_TTL_MINUTES = 60;

    public function compute(int $confidence = 95, int $forecastMonths = 72, string $metric = 'demand'): array
    {
        $metric = in_array($metric, ['revenue', 'product_sales', 'product_revenue'], true) ? $metric : 'demand';
        $confidence = array_key_exists($confidence, self::Z_SCORES) ? $confidence : 95;
        $cacheKey = $metric.':'.$confidence.':'.$forecastMonths;

        if (array_key_exists($cacheKey, $this->computeCache)) {
            return $this->computeCache[$cacheKey];
        }

        $z = self::Z_SCORES[$confidence];
        $unit = match ($metric) {
            'revenue', 'product_revenue' => 'currency',
            'product_sales' => 'units',
            default => 'orders',
        };

        $series = $this->monthlySeries($metric);

        if ($series->count() < self::SEASONAL_PERIOD * 2) {
            $result = $this->empty($confidence, $metric);
            $this->computeCache[$cacheKey] = $result;

            return $result;
        }

        $n = $series->count();
        $ys = $series->pluck('value')->all();

        // The dashboard prefers the Python SARIMA forecast because it is the same model the app is
        // designed around. In the Render deployment pattern, the heavy Python fit is generated by a
        // queued background job and cached so the HTTP request stays fast and under the platform timeout.
        $pythonForecast = $this->cachedPythonForecast($metric, $ys, $forecastMonths, $confidence);
        $pythonDiagnostics = $this->cachedPythonDiagnostics($metric, $ys, 12);

        if ((! is_array($pythonForecast) || empty($pythonForecast)) && ! $this->hasCachedPythonSnapshot($metric, $ys, $forecastMonths, $confidence)) {
            $this->queuePythonSnapshot($metric, $ys, $forecastMonths, $confidence);
        }

        $accuracy = [
            'available' => false,
            'mae' => null,
            'mse' => null,
            'rmse' => null,
            'mape' => null,
            'holdoutMonths' => 0,
        ];

        $lastDate = $series->last()['date'];
        $rawForecast = is_array($pythonForecast) ? $pythonForecast : [];

        $forecast = collect($rawForecast)->values()->map(function ($point, $i) use ($lastDate) {
            $date = $lastDate->copy()->addMonths($i + 1);
            $value = max(0, (float) ($point['value'] ?? 0));

            return [
                'date' => $date,
                'label' => $date->format('M Y'),
                'value' => round($value, 1),
                'lower' => round(max(0, (float) ($point['lower'] ?? $value)), 1),
                'upper' => round(max((float) ($point['upper'] ?? $value), $value), 1),
            ];
        });

        if ($forecast->isEmpty()) {
            $result = $this->empty($confidence, $metric, true);
            $this->computeCache[$cacheKey] = $result;

            return $result;
        }

        // Descriptive analytics below are computed directly from history (independent of the ARIMA forecast above).
        [$intercept, $slope] = $this->linearRegression(range(0, $n - 1), $ys);
        $trendAt = fn (int $x) => $intercept + $slope * $x;

        // Seasonal index per calendar month (1-12), multiplicative, normalized to average 1.0.
        $ratiosByMonth = collect(range(1, 12))->mapWithKeys(fn ($m) => [$m => collect()]);
        foreach ($series as $i => $point) {
            $trendVal = $trendAt($i);
            if ($trendVal > 0.01) {
                $ratiosByMonth[$point['month']]->push($point['value'] / $trendVal);
            }
        }
        $seasonalIndex = $ratiosByMonth->map(fn ($r) => $r->count() ? $r->avg() : 1.0);
        $avgIndex = $seasonalIndex->avg() ?: 1.0;
        $seasonalIndex = $seasonalIndex->map(fn ($v) => $v / $avgIndex);

        $values = $series->pluck('value');
        $mean = $values->avg();
        $median = $this->median($values->all());
        $stdDev = $this->stdDev($values->all());
        $variance = $stdDev ** 2;

        $peakMonthNum = $seasonalIndex->sortDesc()->keys()->first();
        $troughMonthNum = $seasonalIndex->sort()->keys()->first();
        $monthName = fn ($num) => Carbon::create()->month($num)->format('F');
        $avgValueForMonth = fn (int $num) => $series->where('month', $num)->pluck('value')->avg() ?? 0;

        $trendLabel = match (true) {
            $slope > 0.05 => 'Positive',
            $slope < -0.05 => 'Negative',
            default => 'Flat',
        };

        $displayValue = fn ($value) => match ($unit) {
            'currency' => 'PHP '.number_format($value, 0),
            'units' => number_format($value, 1).' units',
            default => number_format($value, 1).' orders',
        };

        $projectedPerYear = round($forecast->avg('value') * 12, 0);
        $annualAvg = round($mean * 12, 1);
        $baselineGrowthPercent = $annualAvg > 0 ? round((($projectedPerYear - $annualAvg) / $annualAvg) * 100, 1) : null;

        // Calendar-month profile (Jan-Dec) used by the "actual vs. forecasted" seasonal chart:
        // historical actual is the average of that calendar month across all history years;
        // forecast/ciUpper average that calendar month across the forecast horizon. A month
        // with no data on either side is left null so the chart can show a gap instead of a zero.
        $monthlyChart = collect(range(1, 12))->map(function ($m) use ($series, $forecast) {
            $actualVals = $series->where('month', $m)->pluck('value');
            $forecastPoints = $forecast->filter(fn ($p) => (int) $p['date']->format('n') === $m);

            return [
                'month' => Carbon::create()->month($m)->format('M'),
                'actual' => $actualVals->count() ? round($actualVals->avg(), 1) : null,
                'forecast' => $forecastPoints->count() ? round($forecastPoints->avg('value'), 1) : null,
                'ciUpper' => $forecastPoints->count() ? round($forecastPoints->avg('upper'), 1) : null,
            ];
        })->values();

        $result = [
            'metric' => $metric,
            'unit' => $unit,
            'confidence' => $confidence,
            'hasData' => true,
            'history' => $series->map(fn ($p) => ['label' => $p['date']->format('M Y'), 'value' => $p['value'], 'display' => $displayValue($p['value'])])->values(),
            'forecast' => $forecast->map(fn ($p) => ['label' => $p['label'], 'value' => $p['value'], 'display' => $displayValue($p['value'])])->values(),
            'forecastBand' => $forecast,
            'monthlyChart' => $monthlyChart,
            'forecastPeriodLabel' => $forecast->first()['date']->format('M Y').' – '.$forecast->last()['date']->format('M Y'),
            'forecastYears' => max(1, round($forecastMonths / 12)),
            'forecastTotal' => round($forecast->sum('value'), 2),
            'avgProjectedPerYear' => $projectedPerYear,
            'baselineGrowthPercent' => $baselineGrowthPercent,
            'peakMonth' => $monthName($peakMonthNum),
            'peakValue' => round($avgValueForMonth($peakMonthNum), 1),
            'peakSeasonalIndex' => round($seasonalIndex[$peakMonthNum], 2),
            'troughMonth' => $monthName($troughMonthNum),
            'troughValue' => round($avgValueForMonth($troughMonthNum), 1),
            'troughSeasonalIndex' => round($seasonalIndex[$troughMonthNum], 2),
            'trendLabel' => $trendLabel,
            'trendComponent' => $slope,
            'annualAvg' => $annualAvg,
            'ciWidth' => round($forecast->avg(fn ($p) => $p['upper'] - $p['lower']), 1),
            'ciUpperAvg' => round($forecast->avg('upper'), 1),
            'ciLowerAvg' => round($forecast->avg('lower'), 1),
            'mean' => $mean,
            'median' => $median,
            'stdDev' => $stdDev,
            'variance' => $variance,
            'maxObserved' => $values->max(),
            'seasonalStrength' => round($seasonalIndex->max() - $seasonalIndex->min(), 2),
            'sampleSize' => $n,
            'modelOrder' => 'SARIMA (Python)',
            'generatedAt' => $this->cachedPythonGeneratedAt($metric, $ys, $forecastMonths, $confidence),
            'diagnostics' => $pythonDiagnostics['diagnostics'] ?? null,
            'stationary' => $pythonDiagnostics['diagnostics']['stationary'] ?? null,
            'adfPValue' => $pythonDiagnostics['diagnostics']['adf_pvalue'] ?? null,
            'selectedOrder' => $pythonDiagnostics['diagnostics']['selected_order'] ?? null,
            'aic' => $pythonDiagnostics['diagnostics']['aic'] ?? null,
            'bic' => $pythonDiagnostics['diagnostics']['bic'] ?? null,
            'ljungBoxPValue' => $pythonDiagnostics['diagnostics']['ljung_box_pvalue'] ?? null,
            'residualOk' => $pythonDiagnostics['diagnostics']['residual_ok'] ?? null,
            'accuracyAvailable' => $accuracy['available'],
            'mae' => $accuracy['mae'],
            'mse' => $accuracy['mse'] ?? null,
            'rmse' => $accuracy['rmse'],
            'mape' => $accuracy['mape'],
            'holdoutMonths' => $accuracy['holdoutMonths'],
        ];

        $this->computeCache[$cacheKey] = $result;

        return $result;
    }

    public function refreshSnapshot(int $confidence, int $forecastMonths, string $metric): bool
    {
        $ys = $this->monthlySeries($metric)->pluck('value')->all();

        if (count($ys) < self::SEASONAL_PERIOD * 2) {
            return false;
        }

        $fingerprint = $this->seriesFingerprint($ys);
        Cache::forget('forecast:python:'.$metric.':'.$forecastMonths.':'.$confidence.':'.$fingerprint);
        Cache::forget('forecast:diagnostics:'.$metric.':12:'.$fingerprint);
        Cache::forget('forecast:generated:'.$metric.':'.$forecastMonths.':'.$confidence.':'.$fingerprint);
        Cache::forget('forecast:queue:'.$metric.':'.$forecastMonths.':'.$confidence.':'.$fingerprint);

        $this->queuePythonSnapshot($metric, $ys, $forecastMonths, $confidence);

        return true;
    }

    public function snapshotStatus(int $confidence, int $forecastMonths, string $metric): array
    {
        $metric = in_array($metric, ['revenue', 'product_sales'], true) ? $metric : 'demand';
        $ys = $this->monthlySeries($metric)->pluck('value')->all();

        if (count($ys) < self::SEASONAL_PERIOD * 2) {
            return ['ready' => true, 'generatedAt' => null];
        }

        $ready = $this->hasCachedPythonSnapshot($metric, $ys, $forecastMonths, $confidence);

        return [
            'ready' => $ready,
            'generatedAt' => $ready ? $this->cachedPythonGeneratedAt($metric, $ys, $forecastMonths, $confidence) : null,
        ];
    }

    private function queuePythonSnapshot(string $metric, array $ys, int $forecastMonths, int $confidence): void
    {
        $lockKey = 'forecast:queue:'.$metric.':'.$forecastMonths.':'.$confidence.':'.$this->seriesFingerprint($ys);

        if (! Cache::get($lockKey, false)) {
            Cache::put($lockKey, true, now()->addMinutes(10));
            GenerateForecastSnapshot::dispatch($metric, $ys, $forecastMonths, self::SEASONAL_PERIOD, $confidence);
        }
    }

    private function hasCachedPythonSnapshot(string $metric, array $ys, int $forecastMonths, int $confidence): bool
    {
        $forecastKey = 'forecast:python:'.$metric.':'.$forecastMonths.':'.$confidence.':'.$this->seriesFingerprint($ys);
        $diagnosticKey = 'forecast:diagnostics:'.$metric.':12:'.$this->seriesFingerprint($ys);

        return Cache::has($forecastKey) && Cache::has($diagnosticKey);
    }

    protected function cachedPythonForecast(string $metric, array $ys, int $forecastMonths, int $confidence): ?array
    {
        $key = 'forecast:python:'.$metric.':'.$forecastMonths.':'.$confidence.':'.$this->seriesFingerprint($ys);

        return Cache::has($key) ? Cache::get($key) : null;
    }

    private function cachedPythonGeneratedAt(string $metric, array $ys, int $forecastMonths, int $confidence): ?string
    {
        $key = 'forecast:generated:'.$metric.':'.$forecastMonths.':'.$confidence.':'.$this->seriesFingerprint($ys);

        return Cache::get($key);
    }

    protected function cachedPythonDiagnostics(string $metric, array $ys, int $steps): ?array
    {
        $key = 'forecast:diagnostics:'.$metric.':'.$steps.':'.$this->seriesFingerprint($ys);

        return Cache::has($key) ? Cache::get($key) : null;
    }

    /**
     * Day-of-week profile (Mon-Sun) for the "Day-of-Week Patterns" mini-tab on the Job-Order and
     * Product Sales views — full history, not windowed like dailyRevenue(). Index is each
     * weekday's value relative to the metric's average weekday value (~1.0 = no effect), the
     * same convention as compute()'s calendar-month seasonal index.
     */
    public function dayOfWeekPattern(string $metric = 'demand'): array
    {
        $metric = $metric === 'product_sales' ? 'product_sales' : 'demand';

        if ($metric === 'product_sales') {
            $rows = SaleItem::query()
                ->join('sales', 'sales.id', '=', 'sale_items.sale_id')
                ->whereNotNull('sales.sold_at')
                ->selectRaw('DAYOFWEEK(sales.sold_at) as dow, SUM(sale_items.quantity) as c')
                ->groupBy('dow')
                ->pluck('c', 'dow');
        } else {
            $rows = JobOrder::query()
                ->whereNotNull('planned_start_date')
                ->selectRaw('DAYOFWEEK(planned_start_date) as dow, COUNT(*) as c')
                ->groupBy('dow')
                ->pluck('c', 'dow');
        }

        if ($rows->isEmpty()) {
            return ['hasData' => false, 'metric' => $metric, 'days' => collect()];
        }

        // MySQL's DAYOFWEEK() is 1=Sunday..7=Saturday; reorder Monday-first for a business-week read.
        $order = [2, 3, 4, 5, 6, 7, 1];
        $names = [2 => 'Mon', 3 => 'Tue', 4 => 'Wed', 5 => 'Thu', 6 => 'Fri', 7 => 'Sat', 1 => 'Sun'];

        $mean = collect($order)->map(fn ($d) => (float) ($rows[$d] ?? 0))->avg() ?: 1.0;

        $days = collect($order)->map(fn ($d) => [
            'weekday' => $names[$d],
            'value' => round((float) ($rows[$d] ?? 0), 1),
            'index' => round(((float) ($rows[$d] ?? 0)) / $mean, 2),
        ]);

        return [
            'hasData' => true,
            'metric' => $metric,
            'days' => $days,
            'busiestDay' => $days->sortByDesc('value')->first()['weekday'],
            'quietestDay' => $days->sortBy('value')->first()['weekday'],
        ];
    }

    /**
     * Impact of fixed-date Philippine holidays on the selected metric, for the "Holiday Impacts"
     * mini-tab on the Job-Order / Product Sales views. For every calendar occurrence of each
     * holiday inside the data's date range we average the daily volume over a +/-$windowDays
     * window, then compare that to the all-time daily baseline. A lift of +25% means days around
     * that holiday run a quarter busier than a typical day.
     *
     * Only fixed-date regular holidays are modelled here — movable observances (Holy Week, Eid,
     * Chinese New Year, National Heroes Day) shift year to year and would need a per-year table.
     */
    public function holidayImpact(string $metric = 'demand', int $windowDays = 7): array
    {
        $metric = $metric === 'product_sales' ? 'product_sales' : 'demand';

        $holidays = [
            ['name' => "New Year's Day", 'month' => 1, 'day' => 1],
            ['name' => 'Labor Day', 'month' => 5, 'day' => 1],
            ['name' => 'Independence Day', 'month' => 6, 'day' => 12],
            ['name' => "All Saints' Day", 'month' => 11, 'day' => 1],
            ['name' => 'Bonifacio Day', 'month' => 11, 'day' => 30],
            ['name' => 'Christmas Day', 'month' => 12, 'day' => 25],
            ['name' => 'Rizal Day', 'month' => 12, 'day' => 30],
        ];

        $empty = ['hasData' => false, 'metric' => $metric, 'unit' => $metric === 'product_sales' ? 'units' : 'orders', 'windowDays' => $windowDays, 'baseline' => 0.0, 'holidays' => collect()];

        if ($metric === 'product_sales') {
            $rows = SaleItem::query()
                ->join('sales', 'sales.id', '=', 'sale_items.sale_id')
                ->whereNotNull('sales.sold_at')
                ->selectRaw('DATE(sales.sold_at) as d, SUM(sale_items.quantity) as c')
                ->groupBy('d')
                ->pluck('c', 'd');
        } else {
            $rows = JobOrder::query()
                ->whereNotNull('planned_start_date')
                ->selectRaw('DATE(planned_start_date) as d, COUNT(*) as c')
                ->groupBy('d')
                ->pluck('c', 'd');
        }

        if ($rows->isEmpty()) {
            return $empty;
        }

        // Dense day-by-day map (0-filled) from the first to the last observed date.
        $sortedKeys = $rows->keys()->sort()->values();
        $start = Carbon::parse($sortedKeys->first())->startOfDay();
        $end = Carbon::parse($sortedKeys->last())->startOfDay();

        $daily = [];
        for ($cursor = $start->copy(); $cursor->lessThanOrEqualTo($end); $cursor->addDay()) {
            $key = $cursor->format('Y-m-d');
            $daily[$key] = (float) ($rows[$key] ?? 0);
        }

        $baseline = count($daily) ? array_sum($daily) / count($daily) : 0.0;
        if ($baseline <= 0) {
            return $empty;
        }

        $results = collect($holidays)->map(function ($h) use ($daily, $start, $end, $windowDays, $baseline) {
            $windowValues = [];
            $occurrences = 0;

            for ($year = $start->year; $year <= $end->year; $year++) {
                $date = Carbon::create($year, $h['month'], $h['day']);
                if ($date->copy()->addDays($windowDays)->lt($start) || $date->copy()->subDays($windowDays)->gt($end)) {
                    continue;
                }
                $occurrences++;
                for ($offset = -$windowDays; $offset <= $windowDays; $offset++) {
                    $key = $date->copy()->addDays($offset)->format('Y-m-d');
                    if (array_key_exists($key, $daily)) {
                        $windowValues[] = $daily[$key];
                    }
                }
            }

            $meanDaily = count($windowValues) ? array_sum($windowValues) / count($windowValues) : 0.0;

            return [
                'name' => $h['name'],
                'date' => Carbon::create(2000, $h['month'], $h['day'])->format('M j'),
                'meanDaily' => round($meanDaily, 2),
                'liftPercent' => round((($meanDaily - $baseline) / $baseline) * 100, 1),
                'observations' => $occurrences,
                'sampleDays' => count($windowValues),
            ];
        })
            ->filter(fn ($r) => $r['observations'] > 0)
            ->sortByDesc('liftPercent')
            ->values();

        return [
            'hasData' => $results->isNotEmpty(),
            'metric' => $metric,
            'unit' => $metric === 'product_sales' ? 'units' : 'orders',
            'windowDays' => $windowDays,
            'baseline' => round($baseline, 2),
            'holidays' => $results,
        ];
    }

    /**
     * Real daily revenue over a trailing window, for the "Daily Revenue" tab. Unlike compute()
     * above, this is a plain actuals report — no SARIMA fit, no forecast, no confidence interval.
     * Daily job-order revenue is far noisier than the monthly aggregates the forecasting model
     * is tuned for, so this intentionally just describes what happened rather than projecting
     * what's next. The window ends yesterday (today's total is still incomplete), matching the
     * same "exclude the in-progress period" convention monthlySeries() uses.
     */
    public function dailyRevenue(int $days = 30): array
    {
        $end = Carbon::yesterday()->endOfDay();
        $start = $end->copy()->subDays($days - 1)->startOfDay();

        $rows = JobOrder::query()
            ->whereNotNull('planned_start_date')
            ->where('payment_status', 'paid')
            ->whereBetween('planned_start_date', [$start, $end])
            ->selectRaw('DATE(planned_start_date) as d, SUM(cost) as c')
            ->groupBy('d')
            ->get()
            ->keyBy(fn ($r) => $r->d);

        $series = collect();
        $cursor = $start->copy();
        while ($cursor->lessThanOrEqualTo($end)) {
            $key = $cursor->format('Y-m-d');
            $series->push([
                'date' => $cursor->copy(),
                'label' => $cursor->format('M j'),
                'weekday' => $cursor->format('D'),
                'value' => round((float) ($rows[$key]->c ?? 0), 2),
            ]);
            $cursor->addDay();
        }

        $periodLabel = $start->format('M j').' – '.$end->format('M j, Y');

        if ($series->sum('value') <= 0) {
            return ['hasData' => false, 'days' => $days, 'periodLabel' => $periodLabel, 'series' => $series];
        }

        $values = $series->pluck('value');
        $latest = $series->last();
        $previous = $series->count() > 1 ? $series->slice(-2, 1)->first() : null;
        $peak = $series->sortByDesc('value')->first();
        $low = $series->sortBy('value')->first();

        $recent7 = $values->slice(-7)->sum();
        $prior7 = $series->count() >= 14 ? $values->slice(-14, 7)->sum() : null;

        $byWeekday = $series->groupBy('weekday')->map(fn ($g) => $g->avg('value'));
        $bestWeekday = $byWeekday->sortDesc()->keys()->first();

        return [
            'hasData' => true,
            'days' => $days,
            'periodLabel' => $periodLabel,
            'series' => $series,
            'total' => round($values->sum(), 2),
            'average' => round($values->avg(), 2),
            'latestValue' => $latest['value'],
            'latestLabel' => $latest['label'],
            'dayOverDayPercent' => $previous && $previous['value'] > 0
                ? round((($latest['value'] - $previous['value']) / $previous['value']) * 100, 1)
                : null,
            'peakValue' => $peak['value'],
            'peakLabel' => $peak['label'],
            'lowValue' => $low['value'],
            'lowLabel' => $low['label'],
            'weekOverWeekPercent' => $prior7 && $prior7 > 0
                ? round((($recent7 - $prior7) / $prior7) * 100, 1)
                : null,
            'bestWeekday' => $bestWeekday,
            'bestWeekdayAvg' => round($byWeekday[$bestWeekday] ?? 0, 2),
        ];
    }

    /**
     * "View Details" backing data for the Daily Revenue view. Mirrors the shape of
     * viewDetails() (so the same modal renders it) but describes the trailing daily
     * actuals instead of a forecast: central tendency, a Mon–Sun weekday profile and a
     * week-by-week summary. No stationarity / model-fit sections — daily has no model.
     */
    public function dailyRevenueDetails(int $days = 30): array
    {
        $base = $this->dailyRevenue($days);

        $out = [
            'mode' => 'daily',
            'metric' => 'revenue',
            'title' => 'Sales revenue · daily',
            'unit' => 'PHP',
            'hasData' => $base['hasData'],
            'periodLabel' => $base['periodLabel'],
            'days' => $days,
        ];

        if (! $base['hasData']) {
            return $out;
        }

        $series = $base['series'];
        $values = $series->pluck('value');
        $ys = $values->all();
        $n = count($ys);
        $mean = (float) $values->avg();
        $overallMean = $mean ?: 1.0;
        $stdDev = $this->stdDev($ys);
        [, $slope] = $this->linearRegression(range(0, $n - 1), $ys);

        // Mon–Sun profile: sample size, central tendency, spread and an index (weekday mean
        // relative to the overall daily mean, ~1.0 = an average day).
        $order = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
        $byWeekday = $series->groupBy('weekday');
        $weekdayProfile = collect($order)->map(function ($wd) use ($byWeekday, $overallMean) {
            $vals = ($byWeekday[$wd] ?? collect())->pluck('value')->values();
            $wdMean = $vals->count() ? (float) $vals->avg() : 0.0;

            return [
                'label' => $wd,
                'n' => $vals->count(),
                'mean' => round($wdMean, 2),
                'sd' => round($this->stdDev($vals->all()), 2),
                'min' => $vals->count() ? round((float) $vals->min(), 2) : 0.0,
                'max' => $vals->count() ? round((float) $vals->max(), 2) : 0.0,
                'index' => round($overallMean > 0 ? $wdMean / $overallMean : 0, 2),
            ];
        })->values();

        $weekdayStrength = round($weekdayProfile->max('index') - $weekdayProfile->min('index'), 2);

        // One row per ISO calendar week in the window, with a 7-slot (Mon–Sun) value series.
        $weeklySummary = $series->groupBy(fn ($p) => $p['date']->format('o-W'))
            ->map(function (Collection $group) {
                $vals = $group->pluck('value');
                $slots = collect(range(1, 7))->map(function ($dow) use ($group) {
                    $match = $group->first(fn ($p) => (int) $p['date']->format('N') === $dow);

                    return round((float) ($match['value'] ?? 0), 2);
                });
                $first = $group->first()['date'];
                $last = $group->last()['date'];
                $label = $first->format('M') === $last->format('M')
                    ? $first->format('M j').'–'.$last->format('j')
                    : $first->format('M j').' – '.$last->format('M j');

                return [
                    'label' => $label,
                    'days' => $vals->count(),
                    'total' => round((float) $vals->sum(), 2),
                    'mean' => round((float) $vals->avg(), 2),
                    'min' => round((float) $vals->min(), 2),
                    'max' => round((float) $vals->max(), 2),
                    'series' => $slots->values()->all(),
                ];
            })->values();

        return $out + [
            'sampleSize' => $n,
            'mean' => round($mean, 2),
            'median' => round($this->median($ys), 2),
            'stdDev' => round($stdDev, 2),
            'variance' => round($stdDev ** 2, 2),
            'maxObserved' => round((float) $values->max(), 2),
            'minObserved' => round((float) $values->min(), 2),
            'trendComponent' => round($slope, 2),
            'weekdayStrength' => $weekdayStrength,
            'weekdayProfile' => $weekdayProfile,
            'weeklySummary' => $weeklySummary,
            'total' => $base['total'],
            'average' => $base['average'],
            'bestWeekday' => $base['bestWeekday'],
        ];
    }

    /**
     * Short-horizon (default 3-month) outlook used by the "Descriptive Analysis" panel.
     * On the Job-Order tab this reports on job-order demand and job-order revenue only. The
     * Sales Revenue tab reports on job-order demand paired with *total* revenue — job-order
     * billing plus product sales combined, since both are real revenue to the business. The
     * Product Sales tab instead reports on product units sold and product sales revenue only,
     * since pairing job-order figures with a product-sales view would be misleading.
     */
    public function descriptiveSummary(int $confidence = 95, int $periodMonths = 3, string $metric = 'demand', ?array $primaryResult = null, ?array $revenueResult = null): array
    {
        $isProductSales = $metric === 'product_sales';
        $isRevenueTab = $metric === 'revenue';

        $primary = $primaryResult ?? $this->compute($confidence, $periodMonths, $isProductSales ? 'product_sales' : 'demand');
        $revenue = $revenueResult ?? $this->compute($confidence, $periodMonths, $isProductSales ? 'product_revenue' : 'revenue');

        if (! $primary['hasData'] || ! $revenue['hasData']) {
            return ['hasData' => false];
        }

        // Product revenue is optional on the Sales Revenue tab (a business with job orders but
        // no recorded product sales yet still gets a valid summary — it just adds nothing).
        $productRevenue = $isRevenueTab ? $this->compute($confidence, $periodMonths, 'product_revenue') : null;
        $extraForecastRevenue = $productRevenue && $productRevenue['hasData'] ? round($productRevenue['forecast']->sum('value'), 2) : 0.0;

        $forecastDates = $primary['forecastBand']->pluck('date')->values();
        $periodLabel = $forecastDates->count() > 1
            ? $forecastDates->first()->format('M').' – '.$forecastDates->last()->format('M')
            : $forecastDates->first()->format('M');

        $primaryCount = (int) round($primary['forecast']->sum('value'));
        $estRevenue = round($revenue['forecast']->sum('value'), 2) + $extraForecastRevenue;
        $avgTicket = $primaryCount > 0 ? round($estRevenue / $primaryCount) : 0;

        $lastYearDates = $forecastDates->map(fn (Carbon $d) => $d->copy()->subYear());
        $priorDates = collect(range($forecastDates->count(), 1))
            ->map(fn ($i) => $forecastDates->first()->copy()->subMonths($i));

        $extraLastYearRevenue = $isRevenueTab ? $this->actualProductRevenue($lastYearDates) : 0.0;
        $extraPriorRevenue = $isRevenueTab ? $this->actualProductRevenue($priorDates) : 0.0;

        $lastYearPrimary = $isProductSales ? $this->actualProductUnits($lastYearDates) : $this->actualCount($lastYearDates);
        $lastYearRevenue = ($isProductSales ? $this->actualProductRevenue($lastYearDates) : $this->actualRevenue($lastYearDates)) + $extraLastYearRevenue;
        $priorRevenue = ($isProductSales ? $this->actualProductRevenue($priorDates) : $this->actualRevenue($priorDates)) + $extraPriorRevenue;

        return [
            'hasData' => true,
            'periodLabel' => $periodLabel,
            'periodMonths' => $forecastDates->count(),
            'primaryLabel' => $isProductSales ? 'Units Sold' : 'Job-Order',
            'primaryCount' => $primaryCount,
            'primaryYoyPercent' => $lastYearPrimary > 0
                ? round((($primaryCount - $lastYearPrimary) / $lastYearPrimary) * 100, 1)
                : null,
            'estRevenueLabel' => $isProductSales ? 'Est. Sales' : 'Est. Rev.',
            'estRevenue' => $estRevenue,
            'estRevenueCompact' => $this->compactNumber($estRevenue),
            'avgTicket' => $avgTicket,
            'avgTicketCompact' => $this->compactNumber($avgTicket),
            'avgTicketLabel' => $isProductSales ? 'avg. per unit' : 'avg. ticket',
            'vsLastYearPercent' => $lastYearRevenue > 0
                ? round((($estRevenue - $lastYearRevenue) / $lastYearRevenue) * 100, 1)
                : null,
            'vsPriorPeriodPercent' => $priorRevenue > 0
                ? round((($estRevenue - $priorRevenue) / $priorRevenue) * 100, 1)
                : null,
            'trendLabel' => $primary['trendLabel'],
            'trendComponent' => $primary['trendComponent'],
            'peakMonth' => $primary['peakMonth'],
            'peakSeasonalIndex' => $primary['peakSeasonalIndex'],
        ];
    }

    /** Fallback horizon when the details modal is requested without a computed page result. */
    private const VIEW_DETAILS_MONTHS = 72;

    /**
     * Backing data for the "View Details" modal. Forecast statistics use the supplied page
     * result when available, so the modal follows the selected metric and horizon; otherwise
     * a six-year forecast is computed as a fallback.
     */
    public function viewDetails(int $confidence = 95, string $metric = 'demand', ?array $computedResult = null): array
    {
        $metric = in_array($metric, ['revenue', 'product_sales'], true) ? $metric : 'demand';

        $title = match ($metric) {
            'revenue' => 'Sales revenue',
            'product_sales' => 'Product sales demand',
            default => 'Job order demand',
        };
        $unit = match ($metric) {
            'revenue' => 'PHP',
            'product_sales' => 'units',
            default => 'orders',
        };

        $computed = $computedResult ?? $this->compute($confidence, self::VIEW_DETAILS_MONTHS, $metric);
        $forecast = $computed['hasData'] ? $computed['forecastBand'] : collect();

        if ($forecast->isEmpty()) {
            return ['mode' => 'monthly', 'hasData' => false, 'metric' => $metric, 'title' => $title, 'unit' => $unit];
        }

        // Descriptive stats below are all computed over the forecast values, not history.
        $n = $forecast->count();
        $values = $forecast->pluck('value');
        $ys = $values->all();
        $mean = (float) $values->avg();
        $overallMean = $mean ?: 1.0;
        $stdDev = $this->stdDev($ys);
        [, $slope] = $this->linearRegression(range(0, $n - 1), $ys);

        $startYear = $forecast->first()['date']->year;
        $endYear = $forecast->last()['date']->year;
        $periodLabel = $startYear === $endYear ? (string) $startYear : $startYear.' – '.$endYear;

        // Per calendar-month (1-12) profile of the forecast: each month recurs once per
        // forecast year, so n is the number of horizon years. The index is the month's mean
        // relative to the overall forecast mean (~1.0 = no seasonal effect).
        $monthlyProfile = collect(range(1, 12))->map(function ($m) use ($forecast, $overallMean) {
            $vals = $forecast->filter(fn ($p) => (int) $p['date']->format('n') === $m)->pluck('value')->values();
            $monthMean = $vals->count() ? (float) $vals->avg() : 0.0;

            return [
                'month' => Carbon::create()->month($m)->format('M'),
                'n' => $vals->count(),
                'mean' => round($monthMean, 1),
                'sd' => round($this->stdDev($vals->all()), 2),
                'min' => $vals->count() ? round((float) $vals->min(), 1) : 0.0,
                'max' => $vals->count() ? round((float) $vals->max(), 1) : 0.0,
                'index' => round($overallMean > 0 ? $monthMean / $overallMean : 0, 2),
            ];
        })->values();

        $seasonalStrength = round($monthlyProfile->max('index') - $monthlyProfile->min('index'), 2);

        // One row per forecast year (the first and last may be partial), with a 12-slot
        // value series for a sparkline.
        $annualSummary = $forecast->groupBy(fn ($p) => $p['date']->format('Y'))
            ->map(function (Collection $group, $year) {
                $vals = $group->pluck('value');
                $byMonth = collect(range(1, 12))->map(function ($m) use ($group) {
                    $match = $group->first(fn ($p) => (int) $p['date']->format('n') === $m);

                    return round((float) ($match['value'] ?? 0), 1);
                });

                return [
                    'year' => (string) $year,
                    'months' => $vals->count(),
                    'total' => round((float) $vals->sum(), 1),
                    'mean' => round((float) $vals->avg(), 1),
                    'min' => round((float) $vals->min(), 1),
                    'max' => round((float) $vals->max(), 1),
                    'series' => $byMonth->values()->all(),
                ];
            })->values();

        $series = $this->monthlySeries($metric);
        $diagnostics = $computed['diagnostics'] ?? [];
        $order = $diagnostics['order'] ?? [];
        $seasonalOrder = $diagnostics['seasonal_order'] ?? [];
        if (($order === [] || $seasonalOrder === []) && preg_match('/SARIMA\((\d+),\s*(\d+),\s*(\d+)\)\((\d+),\s*(\d+),\s*(\d+),\s*(\d+)\)/', (string) ($diagnostics['selected_order'] ?? ''), $matches)) {
            $order = array_map('intval', array_slice($matches, 1, 3));
            $seasonalOrder = array_map('intval', array_slice($matches, 4, 4));
        }

        return [
            'mode' => 'monthly',
            'hasData' => true,
            'metric' => $metric,
            'title' => $title,
            'unit' => $unit,
            'periodLabel' => $periodLabel,
            'horizonYears' => (int) round($n / 12),
            'sampleSize' => $n,
            'historyMonths' => $series->count(),

            // Central tendency and dispersion of the selected forecast horizon.
            'mean' => round($mean, 1),
            'median' => round($this->median($ys), 1),
            'stdDev' => round($stdDev, 2),
            'variance' => round($stdDev ** 2, 1),
            'maxObserved' => round((float) $values->max()),
            'minObserved' => round((float) $values->min()),
            'seasonalStrength' => $seasonalStrength,
            'trendComponent' => round($slope, 2),

            'monthlyProfile' => $monthlyProfile,
            'annualSummary' => $annualSummary,

            // Stationarity
            'diffOrder' => $order[1] ?? null,
            'seasonalDiffOrder' => $seasonalOrder[1] ?? null,
            'seasonalPeriod' => $seasonalOrder[3] ?? self::SEASONAL_PERIOD,
            'adfStatistic' => $diagnostics['adf_statistic'] ?? null,
            'adfPValue' => $diagnostics['adf_pvalue'] ?? null,
            'isStationary' => $diagnostics['stationary'] ?? null,

            // Model fit
            'modelOrder' => $diagnostics['selected_order'] ?? '—',
            'aic' => $diagnostics['aic'] ?? null,
            'bic' => $diagnostics['bic'] ?? null,
            'candidateOrdersChecked' => $diagnostics['candidate_orders_checked'] ?? null,
            'accuracyAvailable' => false,
            'mae' => null,
            'mse' => null,
            'rmse' => null,
            'mape' => null,
            'holdoutMonths' => 0,
        ];
    }

    /**
     * Top job-order services by volume over the trailing $months (excluding the
     * in-progress current month, matching monthlySeries), for the "What's in demand?"
     * panel. Each item's changePercent compares its most recent half of the window
     * against its earlier half.
     */
    public function topServices(int $months = 6, int $limit = 5): array
    {
        $key = "forecast:top-services:{$months}:{$limit}:".Carbon::now()->format('Y-m');

        return Cache::remember($key, now()->addMinutes(self::MODEL_CACHE_TTL_MINUTES), fn () => $this->computeTopServices($months, $limit));
    }

    private function computeTopServices(int $months, int $limit): array
    {
        $end = Carbon::now()->startOfMonth()->subMonth();
        $start = $end->copy()->subMonths($months - 1);

        $rows = JobOrder::query()
            ->join('services', 'services.id', '=', 'job_orders.service_id')
            ->whereNotNull('job_orders.planned_start_date')
            ->whereBetween('job_orders.planned_start_date', [$start->copy()->startOfMonth(), $end->copy()->endOfMonth()])
            ->selectRaw('services.name as service, YEAR(job_orders.planned_start_date) as y, MONTH(job_orders.planned_start_date) as m, COUNT(*) as c')
            ->groupBy('services.name', 'y', 'm')
            ->get();

        if ($rows->isEmpty()) {
            return [];
        }

        $half = (int) ceil($months / 2);

        return $rows->groupBy('service')
            ->map(function (Collection $group, string $service) use ($months, $half, $start) {
                $monthly = collect();
                $cursor = $start->copy();
                for ($i = 0; $i < $months; $i++) {
                    $y = (int) $cursor->format('Y');
                    $m = (int) $cursor->format('n');
                    $match = $group->first(fn ($r) => (int) $r->y === $y && (int) $r->m === $m);
                    $monthly->push((float) ($match->c ?? 0));
                    $cursor->addMonth();
                }

                $recentHalf = $monthly->slice(-$half)->sum();
                $priorHalf = $monthly->slice(0, $months - $half)->sum();
                $changePercent = $priorHalf > 0
                    ? round((($recentHalf - $priorHalf) / $priorHalf) * 100, 1)
                    : ($recentHalf > 0 ? 100.0 : 0.0);

                return [
                    'service' => $service,
                    'volume' => (int) $monthly->sum(),
                    'trend' => $monthly->values()->all(),
                    'changePercent' => $changePercent,
                ];
            })
            ->sortByDesc('volume')
            ->take($limit)
            ->values()
            ->all();
    }

    /**
     * Top-selling product categories by units sold over the trailing $months, for the "What's
     * in demand?" panel on the Product Sales tab. Same shape and trend/changePercent logic as
     * topServices(), just grouped by product category instead of job-order service.
     */
    public function topProductCategories(int $months = 6, int $limit = 5): array
    {
        $key = "forecast:top-categories:{$months}:{$limit}:".Carbon::now()->format('Y-m');

        return Cache::remember($key, now()->addMinutes(self::MODEL_CACHE_TTL_MINUTES), fn () => $this->computeTopProductGrouping($months, $limit, byCategory: true));
    }

    /**
     * Top-selling individual products by units sold over the trailing $months, for the "What's
     * in demand?" panel on the Product Sales tab. Same shape as topProductCategories(), grouped
     * by the product's name as recorded on the sale (not a live product lookup, so renamed or
     * deleted products still show correctly for past sales).
     */
    public function topProducts(int $months = 6, int $limit = 5): array
    {
        $key = "forecast:top-products:{$months}:{$limit}:".Carbon::now()->format('Y-m');

        return Cache::remember($key, now()->addMinutes(self::MODEL_CACHE_TTL_MINUTES), fn () => $this->computeTopProductGrouping($months, $limit, byCategory: false));
    }

    private function computeTopProductGrouping(int $months, int $limit, bool $byCategory): array
    {
        $end = Carbon::now()->startOfMonth()->subMonth();
        $start = $end->copy()->subMonths($months - 1);

        $query = SaleItem::query()
            ->join('sales', 'sales.id', '=', 'sale_items.sale_id')
            ->whereNotNull('sales.sold_at')
            ->whereBetween('sales.sold_at', [$start->copy()->startOfMonth(), $end->copy()->endOfMonth()]);

        if ($byCategory) {
            $rows = $query->join('products', 'products.id', '=', 'sale_items.product_id')
                ->join('categories', 'categories.id', '=', 'products.category_id')
                ->selectRaw('categories.name as grouping_key, YEAR(sales.sold_at) as y, MONTH(sales.sold_at) as m, SUM(sale_items.quantity) as c')
                ->groupBy('categories.name', 'y', 'm')
                ->get();
        } else {
            $rows = $query->selectRaw('sale_items.product_name as grouping_key, YEAR(sales.sold_at) as y, MONTH(sales.sold_at) as m, SUM(sale_items.quantity) as c')
                ->groupBy('sale_items.product_name', 'y', 'm')
                ->get();
        }

        if ($rows->isEmpty()) {
            return [];
        }

        $half = (int) ceil($months / 2);

        return $rows->groupBy('grouping_key')
            ->map(function (Collection $group, string $grouping) use ($months, $half, $start) {
                $monthly = collect();
                $cursor = $start->copy();
                for ($i = 0; $i < $months; $i++) {
                    $y = (int) $cursor->format('Y');
                    $m = (int) $cursor->format('n');
                    $match = $group->first(fn ($r) => (int) $r->y === $y && (int) $r->m === $m);
                    $monthly->push((float) ($match->c ?? 0));
                    $cursor->addMonth();
                }

                $recentHalf = $monthly->slice(-$half)->sum();
                $priorHalf = $monthly->slice(0, $months - $half)->sum();
                $changePercent = $priorHalf > 0
                    ? round((($recentHalf - $priorHalf) / $priorHalf) * 100, 1)
                    : ($recentHalf > 0 ? 100.0 : 0.0);

                return [
                    'service' => $grouping,
                    'volume' => (int) $monthly->sum(),
                    'trend' => $monthly->values()->all(),
                    'changePercent' => $changePercent,
                ];
            })
            ->sortByDesc('volume')
            ->take($limit)
            ->values()
            ->all();
    }

    /**
     * Combined top revenue-earners across job-order services and individual products, for the
     * "Top earners" panel on the Sales Revenue tab's Descriptive Analysis. Unlike topServices()/
     * topProductCategories()/topProducts() (which rank by volume/units), this ranks by revenue —
     * services and product sales aren't on a comparable volume scale, but they are on a revenue
     * one, since both are money the business actually took in.
     */
    public function topEarners(int $months = 6, int $limit = 5): array
    {
        $key = "forecast:top-earners:{$months}:{$limit}:".Carbon::now()->format('Y-m');

        return Cache::remember($key, now()->addMinutes(self::MODEL_CACHE_TTL_MINUTES), fn () => $this->computeTopEarners($months, $limit));
    }

    private function computeTopEarners(int $months, int $limit): array
    {
        $end = Carbon::now()->startOfMonth()->subMonth();
        $start = $end->copy()->subMonths($months - 1);
        $half = (int) ceil($months / 2);

        $buildMonthly = function (Collection $group) use ($months, $half, $start): array {
            $monthly = collect();
            $cursor = $start->copy();
            for ($i = 0; $i < $months; $i++) {
                $y = (int) $cursor->format('Y');
                $m = (int) $cursor->format('n');
                $match = $group->first(fn ($r) => (int) $r->y === $y && (int) $r->m === $m);
                $monthly->push((float) ($match->c ?? 0));
                $cursor->addMonth();
            }

            $recentHalf = $monthly->slice(-$half)->sum();
            $priorHalf = $monthly->slice(0, $months - $half)->sum();
            $changePercent = $priorHalf > 0
                ? round((($recentHalf - $priorHalf) / $priorHalf) * 100, 1)
                : ($recentHalf > 0 ? 100.0 : 0.0);

            return [$monthly->values()->all(), (float) $monthly->sum(), $changePercent];
        };

        $serviceRows = JobOrder::query()
            ->join('services', 'services.id', '=', 'job_orders.service_id')
            ->whereNotNull('job_orders.planned_start_date')
            ->where('job_orders.payment_status', 'paid')
            ->whereBetween('job_orders.planned_start_date', [$start->copy()->startOfMonth(), $end->copy()->endOfMonth()])
            ->selectRaw('services.name as grouping_key, YEAR(job_orders.planned_start_date) as y, MONTH(job_orders.planned_start_date) as m, SUM(job_orders.cost) as c')
            ->groupBy('services.name', 'y', 'm')
            ->get();

        $productRows = SaleItem::query()
            ->join('sales', 'sales.id', '=', 'sale_items.sale_id')
            ->whereNotNull('sales.sold_at')
            ->whereBetween('sales.sold_at', [$start->copy()->startOfMonth(), $end->copy()->endOfMonth()])
            ->selectRaw('sale_items.product_name as grouping_key, YEAR(sales.sold_at) as y, MONTH(sales.sold_at) as m, SUM(sale_items.line_total) as c')
            ->groupBy('sale_items.product_name', 'y', 'm')
            ->get();

        $earners = collect();

        foreach ($serviceRows->groupBy('grouping_key') as $label => $group) {
            [$trend, $earned, $changePercent] = $buildMonthly($group);
            if ($earned > 0) {
                $earners->push([
                    'service' => $label,
                    'type' => 'service',
                    'typeLabel' => 'Service completed',
                    'volume' => round($earned, 2),
                    'trend' => $trend,
                    'changePercent' => $changePercent,
                ]);
            }
        }

        foreach ($productRows->groupBy('grouping_key') as $label => $group) {
            [$trend, $earned, $changePercent] = $buildMonthly($group);
            if ($earned > 0) {
                $earners->push([
                    'service' => $label,
                    'type' => 'product',
                    'typeLabel' => 'Product sale',
                    'volume' => round($earned, 2),
                    'trend' => $trend,
                    'changePercent' => $changePercent,
                ]);
            }
        }

        return $earners->sortByDesc('volume')->take($limit)->values()->all();
    }

    private function actualCount(Collection $dates): int
    {
        if ($dates->isEmpty()) {
            return 0;
        }

        return $this->periodQuery($dates)->count();
    }

    private function actualRevenue(Collection $dates): float
    {
        if ($dates->isEmpty()) {
            return 0.0;
        }

        return (float) $this->periodQuery($dates)->where('payment_status', 'paid')->sum('cost');
    }

    private function actualProductUnits(Collection $dates): int
    {
        if ($dates->isEmpty()) {
            return 0;
        }

        return (int) $this->productPeriodQuery($dates)->sum('sale_items.quantity');
    }

    private function actualProductRevenue(Collection $dates): float
    {
        if ($dates->isEmpty()) {
            return 0.0;
        }

        return (float) $this->productPeriodQuery($dates)->sum('sale_items.line_total');
    }

    /**
     * Single query matching SaleItem rows (via their sale's sold_at) whose (year, month) is in
     * the given set of dates, instead of running one query per date. Mirrors periodQuery() for
     * the product-sales side of the descriptive summary.
     */
    private function productPeriodQuery(Collection $dates)
    {
        $periods = $dates->map(fn (Carbon $d) => (int) $d->format('Ym'))->unique()->values()->all();
        $placeholders = implode(',', array_fill(0, count($periods), '?'));

        return SaleItem::query()
            ->join('sales', 'sales.id', '=', 'sale_items.sale_id')
            ->whereNotNull('sales.sold_at')
            ->whereRaw("(YEAR(sales.sold_at) * 100 + MONTH(sales.sold_at)) in ($placeholders)", $periods);
    }

    /**
     * Single query matching JobOrder rows whose (year, month) is in the given set of dates,
     * instead of running one query per date.
     */
    private function periodQuery(Collection $dates)
    {
        $periods = $dates->map(fn (Carbon $d) => (int) $d->format('Ym'))->unique()->values()->all();
        $placeholders = implode(',', array_fill(0, count($periods), '?'));

        return JobOrder::query()
            ->whereNotNull('planned_start_date')
            ->whereRaw("(YEAR(planned_start_date) * 100 + MONTH(planned_start_date)) in ($placeholders)", $periods);
    }

    private function compactNumber(float $value): string
    {
        $abs = abs($value);
        if ($abs >= 1_000_000) {
            return number_format($value / 1_000_000, 2).'M';
        }
        if ($abs >= 1_000) {
            return number_format($value / 1_000, 1).'K';
        }

        return number_format($value, 0);
    }

    /**
     * Fits (or reuses the cached fit of) the SARIMA model for a metric's full history.
     * Independent of forecastMonths/confidence, so the same fit serves every horizon
     * requested for this metric within the TTL.
     */
    private function fittedModel(string $metric, array $ys): Sarima
    {
        $key = 'forecast:model:'.$metric.':'.$this->seriesFingerprint($ys);

        return Cache::remember($key, now()->addMinutes(self::MODEL_CACHE_TTL_MINUTES), function () use ($ys) {
            $model = Sarima::search($ys, self::SEASONAL_PERIOD);
            if ($model === null || ! $model->fitted) {
                // Last-resort fallback for series too short/degenerate for any order search to fit: naive drift ARIMA(0,1,0).
                $model = new Sarima($ys, 0, 1, 0, 0, 0, 0, self::SEASONAL_PERIOD);
                $model->fit();
            }

            return $model;
        });
    }

    private function cachedAccuracy(string $metric, array $ys, int $seasonalPeriod, Sarima $fullModel): array
    {
        $key = 'forecast:accuracy:'.$metric.':'.$this->seriesFingerprint($ys);

        return Cache::remember($key, now()->addMinutes(self::MODEL_CACHE_TTL_MINUTES), fn () => $this->accuracy($ys, $seasonalPeriod, $fullModel));
    }

    private function seriesFingerprint(array $ys): string
    {
        return hash('crc32', implode(',', $ys));
    }

    /**
     * Hold-out backtest: refit on all but the most recent months (using the same order
     * already selected against the full series, rather than re-running the grid search),
     * forecast that held-out window, and score the forecast against what actually happened
     * using MAE, RMSE, and MAPE (MAPE skips any zero-actual month to avoid division by zero).
     */
    private function accuracy(array $ys, int $seasonalPeriod, Sarima $fullModel): array
    {
        $none = ['available' => false, 'mae' => null, 'mse' => null, 'rmse' => null, 'mape' => null, 'holdoutMonths' => 0];

        $n = count($ys);
        $holdout = min(12, max(3, (int) floor($n * 0.2)));
        $trainSize = $n - $holdout;

        if ($trainSize < 4) {
            return $none;
        }

        $train = array_slice($ys, 0, $trainSize);
        $actual = array_slice($ys, $trainSize);

        $model = new Sarima($train, $fullModel->p, $fullModel->d, $fullModel->q, $fullModel->P, $fullModel->D, $fullModel->Q, $seasonalPeriod);
        if (! $model->fit()) {
            $model = new Sarima($train, 0, 1, 0, 0, 0, 0, $seasonalPeriod);
            $model->fit();
        }

        if (! $model->fitted) {
            return $none;
        }

        $predicted = collect($model->forecast($holdout, 1.0))
            ->pluck('value')
            ->map(fn ($v) => max(0, $v))
            ->all();

        $absErrors = [];
        $sqErrors = [];
        $pctErrors = [];
        foreach ($actual as $i => $a) {
            if (! array_key_exists($i, $predicted)) {
                continue;
            }
            $p = $predicted[$i];
            $absErrors[] = abs($a - $p);
            $sqErrors[] = ($a - $p) ** 2;
            if ($a != 0.0) {
                $pctErrors[] = abs(($a - $p) / $a);
            }
        }

        if ($absErrors === []) {
            return $none;
        }

        return [
            'available' => true,
            'mae' => round(array_sum($absErrors) / count($absErrors), 2),
            'mse' => round(array_sum($sqErrors) / count($sqErrors), 2),
            'rmse' => round(sqrt(array_sum($sqErrors) / count($sqErrors)), 2),
            'mape' => $pctErrors !== [] ? round((array_sum($pctErrors) / count($pctErrors)) * 100, 1) : null,
            'holdoutMonths' => $holdout,
        ];
    }

    protected function monthlySeries(string $metric): Collection
    {
        if ($metric === 'product_sales') {
            $query = SaleItem::query()
                ->join('sales', 'sales.id', '=', 'sale_items.sale_id')
                ->whereNotNull('sales.sold_at')
                ->selectRaw('YEAR(sales.sold_at) as y, MONTH(sales.sold_at) as m, SUM(sale_items.quantity) as c');
        } elseif ($metric === 'product_revenue') {
            $query = SaleItem::query()
                ->join('sales', 'sales.id', '=', 'sale_items.sale_id')
                ->whereNotNull('sales.sold_at')
                ->selectRaw('YEAR(sales.sold_at) as y, MONTH(sales.sold_at) as m, SUM(sale_items.line_total) as c');
        } else {
            $query = JobOrder::query()->whereNotNull('planned_start_date');

            if ($metric === 'revenue') {
                $query->where('payment_status', 'paid')
                    ->selectRaw('YEAR(planned_start_date) as y, MONTH(planned_start_date) as m, SUM(cost) as c');
            } else {
                $query->selectRaw('YEAR(planned_start_date) as y, MONTH(planned_start_date) as m, COUNT(*) as c');
            }
        }

        $rows = $query->groupBy('y', 'm')
            ->orderBy('y')->orderBy('m')
            ->get()
            ->keyBy(fn ($r) => sprintf('%04d-%02d', $r->y, $r->m));

        if ($rows->isEmpty()) {
            return collect();
        }

        $first = Carbon::createFromDate((int) $rows->first()->y, (int) $rows->first()->m, 1)->startOfDay();
        $last = Carbon::createFromDate((int) $rows->last()->y, (int) $rows->last()->m, 1)->startOfDay();

        // The current calendar month is still in progress and its totals are necessarily
        // incomplete, so it's excluded to avoid distorting the fit, trend, and backtest.
        $currentMonthStart = Carbon::now()->startOfMonth();
        if ($last->greaterThanOrEqualTo($currentMonthStart)) {
            $last = $currentMonthStart->copy()->subMonth();
        }

        if ($last->lessThan($first)) {
            return collect();
        }

        $series = collect();
        $cursor = $first->copy();
        while ($cursor->lessThanOrEqualTo($last)) {
            $key = $cursor->format('Y-m');
            $series->push([
                'date' => $cursor->copy(),
                'month' => (int) $cursor->format('n'),
                'value' => (float) ($rows[$key]->c ?? 0),
            ]);
            $cursor->addMonth();
        }

        return $series;
    }

    private function linearRegression(array $xs, array $ys): array
    {
        $n = count($xs);
        $sumX = array_sum($xs);
        $sumY = array_sum($ys);
        $sumXY = 0;
        $sumXX = 0;
        foreach ($xs as $i => $x) {
            $sumXY += $x * $ys[$i];
            $sumXX += $x * $x;
        }

        $denominator = ($n * $sumXX - $sumX ** 2) ?: 1;
        $slope = ($n * $sumXY - $sumX * $sumY) / $denominator;
        $intercept = ($sumY - $slope * $sumX) / $n;

        return [$intercept, $slope];
    }

    private function stdDev(array $values): float
    {
        $n = count($values);
        if ($n < 2) {
            return 0.0;
        }
        $mean = array_sum($values) / $n;
        $variance = array_sum(array_map(fn ($v) => ($v - $mean) ** 2, $values)) / ($n - 1);

        return sqrt($variance);
    }

    private function median(array $values): float
    {
        sort($values);
        $n = count($values);
        if ($n === 0) {
            return 0.0;
        }
        $mid = (int) floor(($n - 1) / 2);
        if ($n % 2 === 0) {
            return ($values[$mid] + $values[$mid + 1]) / 2;
        }

        return (float) $values[$mid];
    }

    private function empty(int $confidence, string $metric = 'demand', bool $forecastPending = false): array
    {
        return [
            'metric' => $metric,
            'unit' => match ($metric) {
                'revenue' => 'currency',
                'product_sales' => 'units',
                default => 'orders',
            },
            'confidence' => $confidence,
            'hasData' => false,
            'forecastPending' => $forecastPending,
            'history' => collect(),
            'forecast' => collect(),
            'forecastBand' => collect(),
            'monthlyChart' => collect(),
            'forecastPeriodLabel' => '—',
            'forecastYears' => 0,
            'forecastTotal' => 0,
            'avgProjectedPerYear' => 0,
            'baselineGrowthPercent' => null,
            'peakMonth' => '—',
            'peakValue' => 0,
            'peakSeasonalIndex' => 0,
            'troughMonth' => '—',
            'troughValue' => 0,
            'troughSeasonalIndex' => 0,
            'trendLabel' => '—',
            'trendComponent' => 0,
            'annualAvg' => 0,
            'ciWidth' => 0,
            'ciUpperAvg' => 0,
            'ciLowerAvg' => 0,
            'mean' => 0,
            'median' => 0,
            'stdDev' => 0,
            'variance' => 0,
            'maxObserved' => 0,
            'seasonalStrength' => 0,
            'sampleSize' => 0,
            'modelOrder' => '—',
            'accuracyAvailable' => false,
            'mae' => null,
            'mse' => null,
            'rmse' => null,
            'mape' => null,
            'holdoutMonths' => 0,
        ];
    }
}
